[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
# Improves performance while sacrificing compatibility
#"-Ctarget-cpu=native",
#Pick one of the two following options, prefer mold if available
"-Clink-arg=-fuse-ld=lld",
#"-Clink-arg=-fuse-ld=mold",

# Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]


[target.x86_64-apple-darwin]
rustflags = [
# Improves performance while sacrificing compatibility
#"-Ctarget-cpu=native",

# Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
[target.aarch64-apple-darwin]
rustflags = [
# Improves performance while sacrificing compatibility
#"-Ctarget-cpu=native",

# Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]


[target.x86_64-pc-windows-msvc]
rustflags = [
# Improves performance while sacrificing compatibility
#"-Ctarget-cpu=native",
"-Clink-arg=-fuse-ld=lld",

# Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
